### ISSUE TITLE
Compilation is giving me an error on Linux

### ISSUE THREAD

**Issue by Samuel-de-Oliveira** [oAGoulart/srlua-vc#1]
Hello, I'm trying to compiling this project for Linux, but always I do that the error message appear:

```
srlua.c: In function ‘cannot’:
srlua.c:67:8: error: implicit declaration of function ‘_strerror_s’; did you mean ‘strerror’? [-Wimplicit-function-declaration]
   67 |   if (!_strerror_s(buffer, 96, NULL))
      |        ^~~~~~~~~~~
      |        strerror
srlua.c: In function ‘load’:
srlua.c:95:7: error: implicit declaration of function ‘fopen_s’; did you mean ‘fopen’? [-Wimplicit-function-declaration]
   95 |   if (fopen_s(&f, name, "rb"))
      |       ^~~~~~~
      |            fopen

```

so i need to add anything here?

**Comment by oAGoulart** [comment]
Hi there! This is a modified version of the original srlua (https://web.tecgraf.puc-rio.br/~lhf/ftp/lua/#srlua) code using Visual C++ calls to build it using Visual Studio, if you want srlua with Lua 5.4 on Linux you can download the original code and overwrite the `src/` folder of this repo.

**Comment by Samuel-de-Oliveira** [comment]
Hello @oAGoulart, I Already did it before your response, but thank you anyway :)
